### PR TITLE
Allow for custom colors!

### PR DESCRIPTION
**Pull request by miketsprague**
Don't feel obligated to merge this, but I wrote the code so I figured I'd share it if anyone else wants to use it.  It's *fairly* clean, but it's definitely not a perfect solution.  I attempted to leave as little footprint as possible, so I left all of the images the same color and changed each button's renderingMode to `UIImageRenderingModeAlwaysTemplate` to take on the tintColor of the button.

## Detailed summary of changes
* Removed `+ (UIColor *)orangeColor` and replaced it with `+ (UIColor *)tintColor` in `TGCameraColor.m`
* Exposed `+ (UIColor *)tintColor` and `+ (void)setTintColor:(UIColor*)tintColor` in `TGCameraColor.h`
* Created `TGTintedButton` class which tints the images and backgroundImages using `[TGCameraColor tintColor]`, assuming `customTintColorOverride` has not been set.
* Created `TGTintedLabel` which sets the text color to `[TGCameraColor tintColor]`
* Changed the `UIButtons` in the xibs to `TGTintedButtons`
* Changed the `UILabels` in `TGCameraAuthorizationViewController.xib` to `TGTintedLabels`
* Deleted `CameraConfirm.imageset` and changed the image of the confirm button to `CameraShot`<sup>1</sup>
* Created `CameraCheckMark.imageset` and created a `UIImageView` that sits above the confirm button in `TGPhotoViewController.xib` and added the appropriate constraints<sup>1</sup>
* Added `TintColorFromAVCaptureFlashMode` and set `customTintColorOverride` of the flash to be gray when it is "off", and the default tint color when it is "on" or "auto".
* Set the tintColor in `TGInitialViewController.m`

## Usage
Call this method before creating the `TGCameraNavigationController`.  You can call it after, but you have to make sure to invalidate all of the tintable buttons and labels.
```objc
[TGCameraColor setTintColor: [UIColor greenColor]];
```

## Screenshots
image
image
image
image

## Footnotes
[1] - The image tinting mechanism works by setting the image's renderingMode to `UIImageRenderingModeAlwaysTemplate`.  This changes anything in the image that isn't transparent to the tint color.  Since `CameraConfirm.imageset` has a white checkmark (not transparent), when the image gets tinted it looks the exact same as `CameraShot.imageset`.  To get around this, I put the checkmark on a transparent background (`CameraCheckMark.imageset`), set the confirm button's image to `CameraShot.imageset`, and placed an image view with the check mark centered on the button.  This has the caveat that the checkmark does **not** dim when the button is selected.  This obviously isn't ideal, but it works well enough :)

Feel free to respond with any questions / suggestions.

### CODE REVIEW

**Comment by miketsprague** [comment]
Note: I've only tested this on iOS 8, since I don't have a physical iOS 7 device handy.

**Comment by tomisacat** [comment]
@miketsprague on iOS 7 it does not work with tintColor property well, I modified and send pull request to your repo, feel free to merge : )

**Comment by Bruno-Furtado** [comment]
@miketsprague, very good!

The current version gets the last image of the camera roll.
Would you have any idea how to fix it easily?
In tests I did, other than that, everything is very good!
If we can solve this problem I do the merge and send a new version of the project to CocoaPods.

ios camera

**Comment by tomisacat** [comment]
I noticed this PR contains merge conflicts, need I do something to resolve it？

**Comment by Bruno-Furtado** [comment]
@tomisacat,
Can you use the branch [colors](https://github.com/tdginternet/TGCameraViewController/tree/colors)?

**Comment by miketsprague** [comment]
@Bruno-Furtado I fixed the tint issue with the recent image and made a PR for the colors branch.  Let me know if everything looks good!

**Comment by miketsprague** [comment]
^^ If it does you can delete this PR and merge the one into the colors branch

**Comment by Bruno-Furtado** [comment]
Thanks @miketsprague!

**Comment by miketsprague** [comment]
Of course!  Thanks for the camera library @Bruno-Furtado !! :P

**Comment by tomisacat** [comment]
@Bruno-Furtado I got 404 of that page : (

**Comment by Bruno-Furtado** [comment]
@tomisacat,
The branch was excluded.
The change is already on the master and was created to tag 2.2.

**Comment by tomisacat** [comment]
@Bruno-Furtado got it : )

**Pull request merged**
